### DISCUSSION TITLE
Run using docker compose?

### DISCUSSION THREAD

**Discussion by carmolim** [tarampampam/webhook-tester#639] [Q&A]
I want to know if is possible to run this project using docker compose, I already have nginx running in my server and I want to configure it using this network in order to public expose the service, someone can help me to achieve this setup?

I tried something like this:

```yml
name: webhook
services:
  webhook-tester:
    tty: true
    ports:
      - 8080:8080/tcp
    image: ghcr.io/tarampampam/webhook-tester:2
    networks:
      - nginxproxy_default

networks:
  nginxproxy_default:
    external: true

```

Thanks!

**Comment by DonWMason** [comment]
Here's a docker-compose I just got working for this project to:

- Persist URLs
- Use redis for both pubsub and storagedriver
- Serve up via my Traefik reverse proxy.

I figured out the ENVIRONMENT VARIABLES by parsing the command.go file. To get it working, you need to:

- Define 2 docker networks: one for webhook internal traffic and the other for Traefik
- You'll need to replace "webhooks.yourdomain.com" with your URL
- Create a data volume either through Docker or in your filesystem and mount that to the /data folder in the image

```
services:
  webhook:
    container_name: "webhooks"
    image: tarampampam/webhook-tester:latest
    ports:
      - "8098:8080"
    environment:
      - AUTO_CREATE_SESSIONS=true     
      - STORAGE_DRIVER=redis # Allowed Values: memory|fs|redis
      - PUBSUB_DRIVER=redis # Allowed Values: memory|redis
      - FS_STORAGE_DIR=/data
      - REDIS_DSN=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - traefik
      - webhooks
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      - "traefik.http.routers.webhooks.entrypoints=http"
      - "traefik.http.routers.webhooks.rule=Host(\`webhooks.yourdomain.com\`)"
      - "traefik.http.middlewares.webhooks-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.webhooks.middlewares=webhooks-https-redirect"

      - "traefik.http.routers.webhooks-secure.entrypoints=https"
      - "traefik.http.routers.webhooks-secure.rule=Host(\`webhooks.yourdomain.com\`)"
      - "traefik.http.middlewares.webhooks-secure-nosam-network.ipallowlist.sourcerange=0.0.0.0/0"
      - "traefik.http.routers.webhooks-secure.middlewares=webhooks-secure-yourdomain-network"
      - "traefik.http.routers.webhooks-secure.tls=true"
      - "traefik.http.routers.webhooks-secure.service=webhooks"
      - "traefik.http.services.webhooks.loadbalancer.server.port=8080"
      - "traefik.http.services.webhooks.loadbalancer.server.scheme=http"

  redis:
    container_name: "webhooks-redis"
    image: "redis:alpine"
    networks:
      - webhooks
    volumes:
      - ./data:/data

networks:
  traefik:
    external: true
  webhooks:
    external: true

```
