### ISSUE TITLE
Testing New Version in Parallel

### ISSUE THREAD

**Issue by hirenshah** [tarampampam/webhook-tester#596]
I most definitely owe you one, so the least I can do is help test the new version.  Is it possible to run both old and new versions in parallel (Docker stacks set up via Portainer on a Synology NAS)?  If necessary, I can stop the old stack and start the new one for testing.

The current compose is:

```yaml
services:
  webhook-tester:
    image: tarampampam/webhook-tester
    container_name: webhook-tester
    command: --log-json serve --port 8080 --storage-driver redis --pubsub-driver redis
            --redis-dsn redis://redis:6379/0 --max-requests 5000 --max-request-body-size 0
            --ignore-header-prefix X-Forwarded- --ignore-header-prefix X-Reverse-Proxy-
            --create-session 41b37dec-c895-4cfb-a181-1f0220174b43
            --session-ttl 9999h    
    hostname: webhook-tester
    ports: ['8080:8080/tcp']
    restart: unless-stopped
    networks:
      macvlan:
        ipv4_address: 192.168.1.247
      database:

networks:
  database:
    external: true
  macvlan:
    external: true
```

Or is the best option to run a completely independant version?

**Comment by tarampampam** [comment]
Hi there, buddy! 😃 I believe the best strategy for testing the alpha build is to run it locally on different TCP ports and compare them. Do you agree? You can use a compose file like this to set it up:

```yaml
services:
  redis:
    image: docker.io/library/redis:7-alpine
    volumes: [redis-data:/data:rw]
    ports: ['6379/tcp']
    healthcheck: {test: ['CMD', 'redis-cli', 'ping'], interval: 500ms, timeout: 1s}

  v1:
    image: ghcr.io/tarampampam/webhook-tester:1.1.0
    ports: ['8090:8080/tcp'] # open http://127.0.0.1:8090
    environment:
      MAX_REQUESTS: 5000
      STORAGE_DRIVER: redis
      PUBSUB_DRIVER: redis
      REDIS_DSN: redis://redis:6379/0
      CREATE_SESSION: 41b37dec-c895-4cfb-a181-1f0220174b43
      SESSION_TTL: 9999h
    command: --log-json serve --max-request-body-size 0
    depends_on: {redis: {condition: service_healthy}}

  v2:
    image: ghcr.io/tarampampam/webhook-tester:2.0.0-alpha4
    ports: ['8091:8080/tcp'] # open http://127.0.0.1:8091
    environment:
      MAX_REQUESTS: 5000
      STORAGE_DRIVER: redis
      PUBSUB_DRIVER: redis
      REDIS_DSN: redis://redis:6379/0
      SESSION_TTL: 9999h
      MAX_REQUEST_BODY_SIZE: 0
      AUTO_CREATE_SESSIONS: true
      #TUNNEL_DRIVER: ngrok
      #NGROK_AUTHTOKEN: %your-ngrok-token%
    depends_on: {redis: {condition: service_healthy}}

volumes:
  redis-data: {}
```

Create a file named `compose.yml` with the content above and run `docker compose up`. Once you're finished, simply press CTRL+C in the terminal :)
