### ISSUE TITLE
Errors after upgraded to v2

### ISSUE THREAD

**Issue by GabrielRozendo** [tarampampam/webhook-tester#609]
I've just updated to v2.0.0 and adapted setup to make it works.
Read the [release notes](https://github.com/tarampampam/webhook-tester/releases/tag/v2.0.0) and also readme to check the diff/what should I do.

<details><summary>Current config files</summary>
<p>

docker-compose.yml:

```
  webhook:
    restart: unless-stopped
    container_name: webhook
    image: tarampampam/webhook-tester
    ports:
      - "8003:8080/tcp"
    command: serve --port 8080 --storage-driver redis --pubsub-driver redis --redis-dsn redis://redis:6379/0 --auto-create-sessions
    depends_on:
      redis: {condition: service_healthy}
```

Caddy:
```
webhook.mydomain.com {
        import logging

        reverse_proxy / :8003 {
                header_up Host {host}
                header_up X-Real-IP {remote_host}
                header_up X-Forwarded-Ssl "on"
        }
        reverse_proxy /socket.io :8003 {
                transport http {
                        versions 1.1
                }
                header_up Upgrade {http_upgrade}
                header_up Connection "Upgrade"
                header_up Host {host}
        }
        reverse_proxy /ws :8003 {
                header_up Host {host}
                header_up Upgrade websocket
                header_up Connection Upgrade
        }
}
```
</p>
</details> 

My goal is always have a "default fixed session" as I've setup it in other webhook services and dont need to change time in time.
I used to pass `--create-session` arg with a easy id `00000000-0000-0000-0000-000000000000` but as I understand it, `auto-create-sessions` only restore the last ones, right? No way to create a default one?

When accessing the site got errors.
in some moment I could not create any session when accessing webhook.mydomain.com, in other moments it created but could not access any way, refreshing the page many times (and lot errors)

<details><summary>Screenshots</summary>
<p>
On open root site:

![CleanShot 2024-12-10 at 11 54 33](https://github.com/user-attachments/assets/da22d5e3-13fe-451a-8d56-6f93fbee0c66)

After tried the "create" button with default values (same output with destroy enabled and disabled):

![CleanShot 2024-12-10 at 11 54 59](https://github.com/user-attachments/assets/a0076dae-812e-4694-921b-fe927f4defd8)

Help dialog not helping at all (it could display the current version too):
![CleanShot 2024-12-10 at 11 56 38](https://github.com/user-attachments/assets/05144ea9-f10d-4fde-92a7-c5de6c2405ee)

Refreshing for a time and then stops in root again without a session:
![CleanShot 2024-12-10 at 12 19 15](https://github.com/user-attachments/assets/28080458-fd82-41f7-bb03-401f43976922)
</p>
</details>

In docker logs just repeating info access:
`{"level":"info","ts":1733833161.0066981,"logger":"http","msg":"HTTP request processed","useragent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15","host":"webhook.mydomain.com","method":"GET","url":"/","content type":"text/html; charset=utf-8","remote addr":"172.19.0.1:47996","method":"GET","duration":0.000158}`

after this I tried with minimum args:
`command: serve --port 8080` 

Still same errors.
I dont know what I'm doing wrong here, any help could be useful.
I also believe has some bugs but also misconfigured some part I dont know.

A reverse proxy info/helper could avoid some mistakes, I checked the only one I found #305 but it has more than a year ago and in v2 peharps changed any config.

**Comment by tarampampam** [comment]
Thank you for providing such a detailed description of the issue, it's incredibly helpful.

Regarding session auto-creation - when implementing this feature, I assumed a static session ID wouldn't be needed since sessions are now automatically created when a request is received. This design allows users to avoid pre-creating specific session IDs, enabling the webhook tester to capture requests seamlessly. However, I'm curious to understand the challenges you're facing with this approach. Could you elaborate on why having a "default fixed session" is essential for your use case?

As for the Caddy configuration - are you using Caddy as the frontend web server? If so, could you share the reasoning behind adding `/ws` and `/socket.io` rules? This context might help identify potential misconfigurations.

**Comment by GabrielRozendo** [comment]
> since sessions are now automatically created when a request is received.

Thanks, it'd solve my question! I didn't know 

Reading the readme again, it's there:

> --auto-create-sessions | automatically create sessions for incoming requests

### My bad! Sorry

---

I've just pulled the v2.0.1 and recreate the container, it's working now! 🎉

<details><summary>config</summary>
<p>

docker-compose.yml:

```
  webhook:
    restart: unless-stopped
    container_name: webhook
    image: tarampampam/webhook-tester
    ports:
      - "8003:8080/tcp"
    command: start --storage-driver redis --pubsub-driver redis --redis-dsn redis://redis:6379/0 --auto-create-sessions
    depends_on:
      redis: {condition: service_healthy}

```

Caddyfile:

```
webhook.mydomain.com {
    reverse_proxy :8003
}
```

</p>
</details>

Updating in real time with alerts:
> New request received
> From [ip] with method POST

Wonderful. Thank you again for make the webhook available and also for keeping it updated.

---

> However, I'm curious to understand the challenges you're facing with this approach. Could you elaborate on why having a "default fixed session" is essential for your use case?

The parameter "auto create sessions" is enough and it's ok for me now. Thank you again.

About my need of "default fixed session" is:
I use a third part API and I need to setup the webhooks (in sandbox/testing environment), it is done sending a POST with the url for each one of events types (~5). 
So:

- POST ... domain.com/0000/event1 ...
- POST ... domain.com/0000/event2 ...
- [3, 4, 5 ..]

Done. All events in single place, I can see them all together in same session just checking "path", always. Today and next week.
If I'd need to change it every time, with the random id, I'd send a DELETE for each event and then send each POST again with the new url.
Loop it each time the id changes...


I'm closing this issue as no problem left.
